apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: Microservice-learn
build:
  local:
    push: false
  artifacts:
    - image: gauri65/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "index.js"
            dest: .
    - image: gauri65/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "index.js"
            dest: .
    - image: gauri65/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
    - image: gauri65/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "index.js"
            dest: .
    - image: gauri65/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "index.js"
            dest: .
    - image: gauri65/frontend-posts
      context: ./frontend/my-app
      docker:
        dockerfile: Dockerfile
        noCache: false
        pullParent: false
        squash: false
      sync:
        manual:
          - src: "app/**/*.tsx"
            dest: .
          - src: "components/**/*.tsx"
            dest: .

manifests:
  rawYaml:
    - ./infra/k8s/*
portForward:
  - resourceType: service
    resourceName: frontend-posts-srv
    port: 3000
    localPort: 3000
